# Generated by Django 5.2.8 on 2025-12-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['price', 'performance_score'], name='computers_c_price_d76f10_idx'),
        ),
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['manufacturer', 'socket'], name='computers_c_manufac_03b1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['-performance_score', 'price'], name='computers_c_perform_9ebf5d_idx'),
        ),
        migrations.AddIndex(
            model_name='cpu',
            index=models.Index(fields=['socket', 'price'], name='computers_c_socket_d7e8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='gpu',
            index=models.Index(fields=['price', 'performance_score'], name='computers_g_price_8b8acd_idx'),
        ),
        migrations.AddIndex(
            model_name='gpu',
            index=models.Index(fields=['manufacturer', 'memory'], name='computers_g_manufac_2e023d_idx'),
        ),
        migrations.AddIndex(
            model_name='gpu',
            index=models.Index(fields=['-performance_score', 'price'], name='computers_g_perform_3e72b6_idx'),
        ),
        migrations.AddIndex(
            model_name='gpu',
            index=models.Index(fields=['memory', 'price'], name='computers_g_memory_afa6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='motherboard',
            index=models.Index(fields=['socket', 'price'], name='computers_m_socket_a20e20_idx'),
        ),
        migrations.AddIndex(
            model_name='motherboard',
            index=models.Index(fields=['manufacturer', 'form_factor'], name='computers_m_manufac_07b785_idx'),
        ),
        migrations.AddIndex(
            model_name='ram',
            index=models.Index(fields=['capacity', 'price'], name='computers_r_capacit_f34d71_idx'),
        ),
        migrations.AddIndex(
            model_name='ram',
            index=models.Index(fields=['memory_type', 'speed'], name='computers_r_memory__61af2a_idx'),
        ),
    ]
