# Generated by Django 5.0.1 on 2025-12-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_cpu_computers_c_price_d76f10_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='case',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='cooling',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='cooling',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='cooling',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='psu',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='psu',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='psu',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='ram',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='ram',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Уверенность AI (0-1)'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ai_generation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата генерации AI'),
        ),
        migrations.AddField(
            model_name='storage',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='Сгенерировано AI'),
        ),
    ]
