# Generated by Django 5.0.1 on 2025-12-02 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0001_initial'),
        ('peripherals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название конфигурации')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('compatibility_check', models.BooleanField(default=True, verbose_name='Проверка совместимости')),
                ('compatibility_notes', models.TextField(blank=True, verbose_name='Примечания по совместимости')),
                ('is_saved', models.BooleanField(default=False, verbose_name='Сохранена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.case', verbose_name='Корпус')),
                ('cooling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.cooling', verbose_name='Охлаждение')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.cpu', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.gpu', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.motherboard', verbose_name='Материнская плата')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.psu', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computers.ram', verbose_name='Оперативная память')),
                ('storage_primary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_storage', to='computers.storage', verbose_name='Основной накопитель')),
                ('storage_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_storage', to='computers.storage', verbose_name='Дополнительный накопитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Конфигурация ПК',
                'verbose_name_plural': 'Конфигурации ПК',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=50, verbose_name='Тип компонента')),
                ('component_id', models.IntegerField(verbose_name='ID компонента')),
                ('reason', models.TextField(verbose_name='Обоснование выбора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.pcconfiguration', verbose_name='Конфигурация')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.chair', verbose_name='Кресло')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_setups', to='recommendations.pcconfiguration', verbose_name='Конфигурация ПК')),
                ('desk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.desk', verbose_name='Стол')),
                ('headset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.headset', verbose_name='Наушники')),
                ('keyboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.keyboard', verbose_name='Клавиатура')),
                ('microphone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.microphone', verbose_name='Микрофон')),
                ('monitor_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_monitor', to='peripherals.monitor', verbose_name='Основной монитор')),
                ('monitor_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_monitor', to='peripherals.monitor', verbose_name='Дополнительный монитор')),
                ('mouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.mouse', verbose_name='Мышь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_setups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('webcam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.webcam', verbose_name='Веб-камера')),
            ],
            options={
                'verbose_name': 'Настройка рабочего места',
                'verbose_name_plural': 'Настройки рабочих мест',
                'ordering': ['-created_at'],
            },
        ),
    ]
