# Generated by Django 5.2.8 on 2025-12-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacesetup',
            name='lighting_recommendation',
            field=models.TextField(blank=True, verbose_name='Рекомендации по освещению'),
        ),
    ]
