# Generated by Django 5.0.1 on 2025-12-04 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peripherals', '0003_capturecard_desklighting_gamepad_headphonestand_and_more'),
        ('recommendations', '0002_workspacesetup_lighting_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcconfiguration',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичная сборка'),
        ),
        migrations.AddField(
            model_name='pcconfiguration',
            name='share_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Код для шаринга'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='capture_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.capturecard', verbose_name='Карта захвата'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='gamepad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.gamepad', verbose_name='Геймпад'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='headphone_stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.headphonestand', verbose_name='Подставка для наушников'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.desklighting', verbose_name='Освещение'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='monitor_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.monitorarm', verbose_name='Кронштейн'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='mousepad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.mousepad', verbose_name='Коврик'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='speakers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.speakers', verbose_name='Колонки'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='stream_deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.streamdeck', verbose_name='Стрим-пульт'),
        ),
        migrations.AddField(
            model_name='workspacesetup',
            name='usb_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peripherals.usbhub', verbose_name='USB-хаб'),
        ),
    ]
