# Generated by Django 5.0.1 on 2025-12-09 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_pcconfiguration_is_public_pcconfiguration_share_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('cpu', 'Процессор'), ('gpu', 'Видеокарта'), ('motherboard', 'Материнская плата'), ('ram', 'Оперативная память'), ('storage', 'Накопитель'), ('psu', 'Блок питания'), ('case', 'Корпус'), ('cooling', 'Охлаждение'), ('monitor', 'Монитор'), ('keyboard', 'Клавиатура'), ('mouse', 'Мышь'), ('headset', 'Наушники')], max_length=50, verbose_name='Тип компонента')),
                ('component_id', models.IntegerField(verbose_name='ID компонента')),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена при добавлении')),
                ('price_alert_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Порог уведомления о цене')),
                ('notify_on_price_drop', models.BooleanField(default=True, verbose_name='Уведомлять о снижении цены')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'component_type', 'component_id')},
            },
        ),
    ]
