# Generated by Django 5.2.8 on 2025-12-09 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('configuration_id', models.IntegerField(null=True)),
                ('context_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чата',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True, verbose_name='ID пользователя')),
                ('request_type', models.CharField(max_length=50, verbose_name='Тип запроса')),
                ('user_type', models.CharField(max_length=50, verbose_name='Тип пользователя')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.JSONField(default=dict, verbose_name='Требования')),
                ('prompt_sent', models.TextField(verbose_name='Отправленный промпт')),
                ('raw_response', models.TextField(verbose_name='Сырой ответ AI')),
                ('parsed_response', models.JSONField(null=True, verbose_name='Распарсенный ответ')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('validation_failed', 'Ошибка валидации'), ('fallback_used', 'Использован fallback'), ('error', 'Ошибка AI')], default='success', max_length=20)),
                ('validation_errors', models.JSONField(default=list, verbose_name='Ошибки валидации')),
                ('fallback_reason', models.TextField(blank=True, verbose_name='Причина fallback')),
                ('model_used', models.CharField(max_length=100, verbose_name='Модель AI')),
                ('response_time_ms', models.IntegerField(null=True, verbose_name='Время ответа (мс)')),
                ('tokens_used', models.IntegerField(null=True, verbose_name='Использовано токенов')),
                ('configuration_id', models.IntegerField(null=True, verbose_name='ID созданной конфигурации')),
                ('configuration_valid', models.BooleanField(default=False, verbose_name='Конфигурация валидна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог AI ответа',
                'verbose_name_plural': 'Логи AI ответов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='recommendat_created_dcbbf6_idx'), models.Index(fields=['status'], name='recommendat_status_d1f66c_idx'), models.Index(fields=['user_id', '-created_at'], name='recommendat_user_id_92a06b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'AI Ассистент'), ('system', 'Системное')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.IntegerField(null=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recommendations.chatsession')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=50)),
                ('component_id', models.IntegerField()),
                ('shop', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['component_type', 'component_id'], name='recommendat_compone_038b31_idx')],
                'unique_together': {('component_type', 'component_id', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='UserBuildHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('configuration_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=50)),
                ('budget_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpu_manufacturer', models.CharField(blank=True, max_length=50)),
                ('gpu_manufacturer', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('user_rating', models.IntegerField(null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История сборки',
                'verbose_name_plural': 'История сборок',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='recommendat_user_id_685c1f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Промпт')),
                ('user_requirements', models.JSONField(default=dict, verbose_name='Требования пользователя')),
                ('raw_response', models.TextField(blank=True, verbose_name='Сырой ответ AI')),
                ('parsed_response', models.JSONField(default=dict, verbose_name='Распарсенный ответ')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('validation_failed', 'Ошибка валидации'), ('fallback_used', 'Использован fallback'), ('error', 'Ошибка')], default='success', max_length=30, verbose_name='Статус')),
                ('validation_errors', models.JSONField(default=list, verbose_name='Ошибки валидации')),
                ('fallback_reason', models.TextField(blank=True, verbose_name='Причина fallback')),
                ('configuration_id', models.IntegerField(null=True, verbose_name='ID созданной конфигурации')),
                ('response_time_ms', models.IntegerField(null=True, verbose_name='Время ответа (мс)')),
                ('tokens_used', models.IntegerField(null=True, verbose_name='Использовано токенов')),
                ('user_approved', models.BooleanField(null=True, verbose_name='Одобрено пользователем')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Отзыв пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог AI',
                'verbose_name_plural': 'Логи AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='recommendat_status_d2ed37_idx'), models.Index(fields=['user', 'created_at'], name='recommendat_user_id_f67863_idx')],
            },
        ),
    ]
