# Generated by Django 5.2.8 on 2025-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_add_ai_log_and_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления включены'),
        ),
    ]
