# Generated by Django 5.0.1 on 2025-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('max_gpu_length', models.IntegerField(blank=True, null=True, verbose_name='Макс. длина видеокарты (мм)')),
                ('fan_slots', models.IntegerField(default=0, verbose_name='Слоты для вентиляторов')),
                ('rgb', models.BooleanField(default=False, verbose_name='RGB подсветка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('cooling_type', models.CharField(choices=[('air', 'Воздушное'), ('aio', 'Водяное (AIO)'), ('custom', 'Кастомное водяное')], max_length=20, verbose_name='Тип')),
                ('socket_compatibility', models.TextField(verbose_name='Совместимые сокеты')),
                ('max_tdp', models.IntegerField(verbose_name='Макс. TDP (Вт)')),
                ('noise_level', models.IntegerField(blank=True, null=True, verbose_name='Уровень шума (дБ)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Система охлаждения',
                'verbose_name_plural': 'Системы охлаждения',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('cores', models.IntegerField(verbose_name='Количество ядер')),
                ('threads', models.IntegerField(verbose_name='Количество потоков')),
                ('base_clock', models.FloatField(verbose_name='Базовая частота (ГГц)')),
                ('boost_clock', models.FloatField(blank=True, null=True, verbose_name='Турбо частота (ГГц)')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('performance_score', models.IntegerField(default=0, verbose_name='Оценка производительности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ['-performance_score'],
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('chipset', models.CharField(max_length=100, verbose_name='Чипсет')),
                ('memory', models.IntegerField(verbose_name='Объем памяти (ГБ)')),
                ('memory_type', models.CharField(max_length=50, verbose_name='Тип памяти')),
                ('core_clock', models.IntegerField(verbose_name='Частота ядра (МГц)')),
                ('boost_clock', models.IntegerField(blank=True, null=True, verbose_name='Boost частота (МГц)')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('recommended_psu', models.IntegerField(verbose_name='Рекомендуемый БП (Вт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('performance_score', models.IntegerField(default=0, verbose_name='Оценка производительности')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ['-performance_score'],
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=100, verbose_name='Чипсет')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('memory_slots', models.IntegerField(verbose_name='Количество слотов памяти')),
                ('max_memory', models.IntegerField(verbose_name='Максимальный объем памяти (ГБ)')),
                ('memory_type', models.CharField(max_length=50, verbose_name='Тип памяти')),
                ('pcie_slots', models.IntegerField(verbose_name='Количество PCIe слотов')),
                ('m2_slots', models.IntegerField(default=0, verbose_name='Количество M.2 слотов')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('wattage', models.IntegerField(verbose_name='Мощность (Вт)')),
                ('efficiency_rating', models.CharField(max_length=50, verbose_name='Сертификат 80 PLUS')),
                ('modular', models.BooleanField(default=False, verbose_name='Модульный')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('memory_type', models.CharField(max_length=50, verbose_name='Тип памяти')),
                ('capacity', models.IntegerField(verbose_name='Объем (ГБ)')),
                ('speed', models.IntegerField(verbose_name='Частота (МГц)')),
                ('modules', models.IntegerField(default=1, verbose_name='Количество модулей')),
                ('cas_latency', models.CharField(blank=True, max_length=50, verbose_name='CAS латентность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('storage_type', models.CharField(choices=[('ssd_nvme', 'SSD NVMe'), ('ssd_sata', 'SSD SATA'), ('hdd', 'HDD')], max_length=20, verbose_name='Тип')),
                ('capacity', models.IntegerField(verbose_name='Объем (ГБ)')),
                ('read_speed', models.IntegerField(blank=True, null=True, verbose_name='Скорость чтения (МБ/с)')),
                ('write_speed', models.IntegerField(blank=True, null=True, verbose_name='Скорость записи (МБ/с)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Накопитель',
                'verbose_name_plural': 'Накопители',
            },
        ),
    ]
